---
- name: (Debian) Include distro-specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'Debian'

- name: (RHEL) Include distro-specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'
  - ansible_distribution != 'Amazon'

- name: (RHEL) Include distro-specific variables (Rocky, AlmaLinux)
  include_vars: "RedHat-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_version.string is version('2.11', '<')
    - ansible_os_family in ['AlmaLinux', 'Rocky']

- name: Define walg_pg_data_dir
  set_fact:
    walg_pg_data_dir: "{{ _walg_pg_data_dir }}"
  when: walg_pg_data_dir is not defined

- name: Define walg_pg_config_path
  set_fact:
    walg_pg_config_path: "{{ _walg_pg_config_path }}"
  when: walg_pg_config_path is not defined

- name: Define walg_pg_service
  set_fact:
    walg_pg_service: "{{ _walg_pg_service }}"
  when: walg_pg_service is not defined

- name: Determine walg_postgres_home_dir variable value
  when: walg_postgres_home_dir is not defined
  block:
    - name: Get user home directory with getent
      shell: "getent passwd {{ walg_user }} | cut -d : -f 6"
      changed_when: false
      register: walg_user_home

    - name: Define walg_postgres_home_dir
      set_fact:
        walg_postgres_home_dir: "{{ walg_user_home.stdout }}"
  # end block
