---
- name: Converge
  hosts: all
  become: yes

  vars:
    walg_user: "{{ postgresql_user }}"
    walg_group: "{{ postgresql_group }}"
    walg_pg_data_dir: "{{ postgresql_data_dir }}"
    walg_pg_config_path: "{{ postgresql_config_path }}"
    walg_pg_service: "{{ postgresql_daemon }}"

  pre_tasks:
    - name: Install Cron and Logrotate
      yum:
        name:
          - cronie
          - logrotate
        state: installed

    - name: Create backup dir
      file:
        path: "/pg_backup"
        state: directory
        mode: 0777

  roles:
    - role: geerlingguy.postgresql
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
